-- Restore the column DEFAULTs db/init.sql declares on a database whose tables were created by the
-- app's ddl-auto=update instead (Hibernate makes columns NOT NULL but gives them no DEFAULT), so
-- hand-written SQL that leaves these columns out behaves the same as on an init.sql database.
-- Idempotent: only sets a DEFAULT where the column exists and has none. Metadata-only, no table
-- rewrite. init.sql already has these DEFAULTs; the same list is in
-- tools/legacy-migration/sql/01_reset_data.sql for migration runs against a not-yet-migrated database.
DO $$
DECLARE
    d record;
BEGIN
    FOR d IN
        SELECT c.table_name, c.column_name, v.dflt
        FROM (VALUES
            ('assemblies', 'created_at', 'NOW()'),
            ('assemblies', 'loaded', 'FALSE'),
            ('assemblies', 'origin', $d$'NATIVE'$d$),
            ('assemblies', 'voided', 'FALSE'),
            ('assembly_lines', 'quantity_loaded', '0'),
            ('audit_logs', 'changed_at', 'NOW()'),
            ('bill_of_material_lines', 'created_at', 'NOW()'),
            ('bill_of_material_lines', 'updated_at', 'NOW()'),
            ('bills_of_materials', 'active', 'TRUE'),
            ('bills_of_materials', 'created_at', 'NOW()'),
            ('bills_of_materials', 'updated_at', 'NOW()'),
            ('brands', 'created_at', 'NOW()'),
            ('brands', 'updated_at', 'NOW()'),
            ('companies', 'active', 'TRUE'),
            ('companies', 'created_at', 'NOW()'),
            ('companies', 'updated_at', 'NOW()'),
            ('customers', 'active', 'TRUE'),
            ('customers', 'created_at', 'NOW()'),
            ('customers', 'updated_at', 'NOW()'),
            ('delivery_receipt_lines', 'quantity_loaded', '0'),
            ('delivery_receipt_lines', 'unit_price', '0'),
            ('delivery_receipts', 'created_at', 'NOW()'),
            ('delivery_receipts', 'loaded', 'FALSE'),
            ('delivery_receipts', 'voided', 'FALSE'),
            ('document_templates', 'active', 'TRUE'),
            ('document_templates', 'created_at', 'NOW()'),
            ('document_templates', 'is_default', 'FALSE'),
            ('document_templates', 'updated_at', 'NOW()'),
            ('employees', 'active', 'TRUE'),
            ('employees', 'created_at', 'NOW()'),
            ('employees', 'updated_at', 'NOW()'),
            ('inventory_adjustment_lines', 'quantity_loaded', '0'),
            ('inventory_adjustments', 'created_at', 'NOW()'),
            ('inventory_adjustments', 'loaded', 'FALSE'),
            ('inventory_adjustments', 'voided', 'FALSE'),
            ('inventory_balances', 'quantity', '0'),
            ('inventory_balances', 'transit_quantity', '0'),
            ('inventory_balances', 'updated_at', 'NOW()'),
            ('inventory_movements', 'created_at', 'NOW()'),
            ('inventory_movements', 'transit_quantity_delta', '0'),
            ('item_categories', 'created_at', 'NOW()'),
            ('item_categories', 'updated_at', 'NOW()'),
            ('item_groups', 'active', 'TRUE'),
            ('item_groups', 'commission_rate', '0'),
            ('item_groups', 'created_at', 'NOW()'),
            ('item_groups', 'focal_commission_rate', '0'),
            ('item_groups', 'updated_at', 'NOW()'),
            ('item_prices', 'created_at', 'NOW()'),
            ('item_prices', 'updated_at', 'NOW()'),
            ('item_skus', 'active', 'TRUE'),
            ('item_skus', 'created_at', 'NOW()'),
            ('item_skus', 'landmark_sku', 'FALSE'),
            ('item_skus', 'rds_sku', 'FALSE'),
            ('item_skus', 'updated_at', 'NOW()'),
            ('items', 'active', 'TRUE'),
            ('items', 'created_at', 'NOW()'),
            ('items', 'updated_at', 'NOW()'),
            ('outlet_delivery_receipt_lines', 'quantity_loaded', '0'),
            ('outlet_delivery_receipt_lines', 'unit_price', '0'),
            ('outlet_delivery_receipts', 'created_at', 'NOW()'),
            ('outlet_delivery_receipts', 'loaded', 'FALSE'),
            ('outlet_delivery_receipts', 'origin', $d$'NATIVE'$d$),
            ('outlet_delivery_receipts', 'voided', 'FALSE'),
            ('outlet_delivery_return_lines', 'quantity_loaded', '0'),
            ('outlet_delivery_return_lines', 'unit_price', '0'),
            ('outlet_delivery_returns', 'created_at', 'NOW()'),
            ('outlet_delivery_returns', 'loaded', 'FALSE'),
            ('outlet_delivery_returns', 'voided', 'FALSE'),
            ('outlet_pull_out_lines', 'quantity_loaded', '0'),
            ('outlet_pull_out_lines', 'unit_price', '0'),
            ('outlet_pull_outs', 'created_at', 'NOW()'),
            ('outlet_pull_outs', 'loaded', 'FALSE'),
            ('outlet_pull_outs', 'origin', $d$'NATIVE'$d$),
            ('outlet_pull_outs', 'voided', 'FALSE'),
            ('outlet_receive_lines', 'quantity_loaded', '0'),
            ('outlet_receives', 'created_at', 'NOW()'),
            ('outlet_receives', 'loaded', 'FALSE'),
            ('outlet_receives', 'voided', 'FALSE'),
            ('permissions', 'created_at', 'NOW()'),
            ('permissions', 'updated_at', 'NOW()'),
            ('pull_out_reasons', 'active', 'TRUE'),
            ('pull_out_reasons', 'created_at', 'NOW()'),
            ('pull_out_reasons', 'updated_at', 'NOW()'),
            ('pull_out_receive_lines', 'quantity_loaded', '0'),
            ('pull_out_receives', 'created_at', 'NOW()'),
            ('pull_out_receives', 'loaded', 'FALSE'),
            ('pull_out_receives', 'origin', $d$'NATIVE'$d$),
            ('pull_out_receives', 'voided', 'FALSE'),
            ('purchase_invoice_lines', 'cost_price', '0'),
            ('purchase_invoice_lines', 'discount_percentage', '0'),
            ('purchase_invoice_lines', 'quantity_loaded', '0'),
            ('purchase_invoices', 'created_at', 'NOW()'),
            ('purchase_invoices', 'discount_percentage', '0'),
            ('purchase_invoices', 'loaded', 'FALSE'),
            ('purchase_invoices', 'payment_status', $d$'UNPAID'$d$),
            ('purchase_invoices', 'voided', 'FALSE'),
            ('purchase_order_lines', 'cost_price', '0'),
            ('purchase_order_lines', 'quantity_loaded', '0'),
            ('purchase_orders', 'created_at', 'NOW()'),
            ('purchase_orders', 'loaded', 'FALSE'),
            ('purchase_orders', 'voided', 'FALSE'),
            ('purchase_receive_lines', 'quantity_loaded', '0'),
            ('purchase_receives', 'created_at', 'NOW()'),
            ('purchase_receives', 'loaded', 'FALSE'),
            ('purchase_receives', 'voided', 'FALSE'),
            ('roles', 'created_at', 'NOW()'),
            ('roles', 'updated_at', 'NOW()'),
            ('stock_transfer_lines', 'quantity_loaded', '0'),
            ('stock_transfer_lines', 'unit_price', '0'),
            ('stock_transfers', 'created_at', 'NOW()'),
            ('stock_transfers', 'loaded', 'FALSE'),
            ('stock_transfers', 'origin', $d$'NATIVE'$d$),
            ('stock_transfers', 'voided', 'FALSE'),
            ('suppliers', 'active', 'TRUE'),
            ('suppliers', 'created_at', 'NOW()'),
            ('suppliers', 'updated_at', 'NOW()'),
            ('transaction_action_definitions', 'active', 'TRUE'),
            ('transaction_action_definitions', 'created_at', 'NOW()'),
            ('transaction_action_definitions', 'sort_order', '0'),
            ('transaction_action_definitions', 'updated_at', 'NOW()'),
            ('transaction_events', 'performed_at', 'NOW()'),
            ('user_preferences', 'updated_at', 'NOW()'),
            ('users', 'created_at', 'NOW()'),
            ('users', 'updated_at', 'NOW()'),
            ('warehouses', 'active', 'TRUE'),
            ('warehouses', 'created_at', 'NOW()'),
            ('warehouses', 'main', 'FALSE'),
            ('warehouses', 'outlet', 'FALSE'),
            ('warehouses', 'updated_at', 'NOW()')
        ) v(tbl, col, dflt)
        JOIN information_schema.columns c
          ON c.table_schema = 'public' AND c.table_name = v.tbl AND c.column_name = v.col
        WHERE c.column_default IS NULL
    LOOP
        EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I SET DEFAULT %s', d.table_name, d.column_name, d.dflt);
    END LOOP;
END $$;
