FROM postgres:17-alpine

ARG DB_USERNAME=admin
ARG DB_PASSWORD=password

ENV POSTGRES_DB=norbiz
ENV POSTGRES_USER=${DB_USERNAME}
ENV POSTGRES_PASSWORD=${DB_PASSWORD}

COPY db/init.sql /docker-entrypoint-initdb.d/init.sql

EXPOSE 5432