-- ============================================================
-- Norbiz — full schema for a fresh database
-- Runs once on first container start via Docker POSTGRES_DB init.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

ALTER DATABASE norbiz SET search_path TO public;

-- ============================================================
-- Security
-- ============================================================

CREATE TABLE IF NOT EXISTS permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by  VARCHAR(100),
    updated_by  VARCHAR(100),
    CONSTRAINT PERMISSIONS_NAME_UQ UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    CONSTRAINT ROLES_NAME_UQ UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT ROLE_PERMISSIONS_ROLE_ID_FK       FOREIGN KEY (role_id)       REFERENCES roles(id)       ON DELETE CASCADE,
    CONSTRAINT ROLE_PERMISSIONS_PERMISSION_ID_FK FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    email        VARCHAR(255) NOT NULL,
    password     VARCHAR(255) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    CONSTRAINT USERS_USERNAME_UQ UNIQUE (username),
    CONSTRAINT USERS_EMAIL_UQ    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT USER_ROLES_USER_ID_FK FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT USER_ROLES_ROLE_ID_FK FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- ============================================================
-- Multi-tenancy: companies
-- ============================================================

CREATE TABLE IF NOT EXISTS companies (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

-- Regular users belong to one company; super/system admins may span many.
CREATE TABLE IF NOT EXISTS user_companies (
    user_id    BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, company_id),
    CONSTRAINT USER_COMPANIES_USER_ID_FK    FOREIGN KEY (user_id)    REFERENCES users(id)     ON DELETE CASCADE,
    CONSTRAINT USER_COMPANIES_COMPANY_ID_FK FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

-- ============================================================
-- Item Categories
-- ============================================================

CREATE TABLE IF NOT EXISTS item_categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT ITEM_CATEGORIES_COMPANY_NAME_UQ UNIQUE (company_id, name),
    CONSTRAINT ITEM_CATEGORIES_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- ============================================================
-- Item Groups
-- ============================================================

CREATE TABLE IF NOT EXISTS item_groups (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id            BIGINT        NOT NULL,
    name                  VARCHAR(255)  NOT NULL,
    description           VARCHAR(255),
    bn_initials           VARCHAR(20),
    commission_rate       NUMERIC(5, 2) NOT NULL DEFAULT 0,
    focal_commission_rate NUMERIC(5, 2) NOT NULL DEFAULT 0,
    active                BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    created_by            VARCHAR(100),
    updated_by            VARCHAR(100),
    CONSTRAINT ITEM_GROUPS_COMPANY_NAME_UQ UNIQUE (company_id, name),
    CONSTRAINT ITEM_GROUPS_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- ============================================================
-- Items
-- ============================================================

CREATE TABLE IF NOT EXISTS items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT       NOT NULL,
    item_category_id BIGINT       NOT NULL,
    item_group_id    BIGINT,
    item_code        VARCHAR(100) NOT NULL,
    name             VARCHAR(255) NOT NULL,
    image_path       VARCHAR(500),
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100),
    CONSTRAINT ITEMS_COMPANY_ITEM_CODE_UQ UNIQUE (company_id, item_code),
    CONSTRAINT ITEMS_COMPANY_ID_FK        FOREIGN KEY (company_id)       REFERENCES companies(id),
    CONSTRAINT ITEMS_ITEM_CATEGORY_ID_FK  FOREIGN KEY (item_category_id) REFERENCES item_categories(id),
    CONSTRAINT ITEMS_ITEM_GROUP_ID_FK     FOREIGN KEY (item_group_id)    REFERENCES item_groups(id)
);

-- SKU codes — unique per item only (several items may share a code); one item can have many SKUs.
-- A SKU may also exist without an item (item_id null), scoped by its company.
CREATE TABLE IF NOT EXISTS item_skus (
    id               BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT         NOT NULL,
    item_id          BIGINT,
    sku_code         VARCHAR(100)   NOT NULL,
    unit_price       NUMERIC(19, 4) NOT NULL,
    item_category_id BIGINT,
    brand_id         BIGINT,
    price_type       VARCHAR(20),
    store_item_code  VARCHAR(100),
    barcode          VARCHAR(100),
    vendor_part      VARCHAR(100),
    rds_description  VARCHAR(255),
    active           BOOLEAN        NOT NULL DEFAULT TRUE,
    rds_sku          BOOLEAN        NOT NULL DEFAULT FALSE,
    landmark_sku     BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100),
    CONSTRAINT ITEM_SKUS_ITEM_SKU_CODE_UQ        UNIQUE (item_id, sku_code),
    CONSTRAINT ITEM_SKUS_COMPANY_ID_FK           FOREIGN KEY (company_id)       REFERENCES companies(id),
    CONSTRAINT ITEM_SKUS_ITEM_ID_FK              FOREIGN KEY (item_id)          REFERENCES items(id) ON DELETE CASCADE,
    CONSTRAINT ITEM_SKUS_ITEM_CATEGORY_ID_FK     FOREIGN KEY (item_category_id) REFERENCES item_categories(id),
    CONSTRAINT ITEM_SKUS_BRAND_ID_FK             FOREIGN KEY (brand_id)         REFERENCES brands(id)
);

-- One row per price type per item
CREATE TABLE IF NOT EXISTS item_prices (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id    BIGINT         NOT NULL,
    price_type VARCHAR(20)    NOT NULL, -- UNIT_PRICE | COST_PRICE | FOCAL_PRICE | MARKDOWN_PRICE
    amount     NUMERIC(19, 4) NOT NULL,
    created_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT ITEM_PRICES_ITEM_PRICE_TYPE_UQ UNIQUE (item_id, price_type),
    CONSTRAINT ITEM_PRICES_ITEM_ID_FK         FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS item_tags (
    item_id BIGINT      NOT NULL,
    tag     VARCHAR(50) NOT NULL,
    PRIMARY KEY (item_id, tag),
    CONSTRAINT ITEM_TAGS_ITEM_ID_FK FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);

-- ============================================================
-- Brands
-- ============================================================

CREATE TABLE IF NOT EXISTS brands (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT BRANDS_COMPANY_NAME_UQ UNIQUE (company_id, name),
    CONSTRAINT BRANDS_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- ============================================================
-- Warehouses
-- ============================================================

CREATE TABLE IF NOT EXISTS warehouses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,
    code       VARCHAR(100),
    name       VARCHAR(255) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT WAREHOUSES_COMPANY_CODE_UQ UNIQUE (company_id, code),
    CONSTRAINT WAREHOUSES_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- ============================================================
-- Employees
-- ============================================================

CREATE TABLE IF NOT EXISTS employees (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    BIGINT       NOT NULL,
    user_id       BIGINT,
    employee_code VARCHAR(100) NOT NULL,
    first_name    VARCHAR(255) NOT NULL,
    last_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255),
    phone         VARCHAR(50),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100),
    CONSTRAINT EMPLOYEES_COMPANY_CODE_UQ UNIQUE (company_id, employee_code),
    CONSTRAINT EMPLOYEES_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT EMPLOYEES_USER_ID_FK      FOREIGN KEY (user_id)    REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS employee_tags (
    employee_id BIGINT      NOT NULL,
    tag         VARCHAR(50) NOT NULL,
    PRIMARY KEY (employee_id, tag),
    CONSTRAINT EMPLOYEE_TAGS_EMPLOYEE_ID_FK FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

-- ============================================================
-- Audit log — append-only record of all entity changes
-- ============================================================

CREATE TABLE IF NOT EXISTS audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(100) NOT NULL,
    entity_id   BIGINT,
    parent_type VARCHAR(100),
    parent_id   BIGINT,
    change_set  VARCHAR(36),
    action      VARCHAR(20)  NOT NULL,
    changed_by  VARCHAR(100),
    changed_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    changes     TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_parent ON audit_logs (parent_type, parent_id);

-- ============================================================
-- Suppliers
-- ============================================================

CREATE TABLE IF NOT EXISTS suppliers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,
    code       VARCHAR(100),
    name       VARCHAR(255) NOT NULL,
    email      VARCHAR(255),
    phone      VARCHAR(50),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT SUPPLIERS_COMPANY_CODE_UQ UNIQUE (company_id, code),
    CONSTRAINT SUPPLIERS_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- ============================================================
-- Customers (includes Outlets, distinguished by `type`)
-- ============================================================

CREATE TABLE IF NOT EXISTS customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,
    code       VARCHAR(100),
    name       VARCHAR(255) NOT NULL,
    type       VARCHAR(20)  NOT NULL, -- CUSTOMER | OUTLET
    email      VARCHAR(255),
    phone      VARCHAR(50),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT CUSTOMERS_COMPANY_CODE_UQ UNIQUE (company_id, code),
    CONSTRAINT CUSTOMERS_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- Main warehouse (Delivery Receipt source, at most one per company) and outlet-owned warehouses.
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS main   BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS outlet BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS WAREHOUSES_COMPANY_MAIN_UQ ON warehouses (company_id) WHERE main;

-- OUTLET customers' own warehouse (auto-created by the app; own identity id, not the customer id).
ALTER TABLE customers ADD COLUMN IF NOT EXISTS warehouse_id BIGINT;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'customers_warehouse_id_fk') THEN
        ALTER TABLE customers ADD CONSTRAINT CUSTOMERS_WAREHOUSE_ID_FK FOREIGN KEY (warehouse_id) REFERENCES warehouses(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'customers_warehouse_uq') THEN
        ALTER TABLE customers ADD CONSTRAINT CUSTOMERS_WAREHOUSE_UQ UNIQUE (warehouse_id);
    END IF;
END $$;

-- ============================================================
-- Inventory core — append-only ledger + running balance cache.
-- Neither table is user-editable; both are only ever written by
-- inventory-posting transactions (e.g. inventory_adjustments below).
-- ============================================================

CREATE TABLE IF NOT EXISTS inventory_movements (
    id                     BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id             BIGINT         NOT NULL,
    item_id                BIGINT         NOT NULL,
    warehouse_id           BIGINT         NOT NULL,
    quantity_delta         NUMERIC(19, 4) NOT NULL,
    transit_quantity_delta NUMERIC(19, 4) NOT NULL DEFAULT 0,
    movement_date          TIMESTAMPTZ    NOT NULL,
    source_type            VARCHAR(50)    NOT NULL,
    source_id              BIGINT         NOT NULL,
    reference_number       VARCHAR(50)    NOT NULL,
    sheet_number           VARCHAR(100),
    notes                  VARCHAR(255),
    created_at             TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    created_by             VARCHAR(100),
    CONSTRAINT INVENTORY_MOVEMENTS_COMPANY_ID_FK   FOREIGN KEY (company_id)   REFERENCES companies(id),
    CONSTRAINT INVENTORY_MOVEMENTS_ITEM_ID_FK      FOREIGN KEY (item_id)      REFERENCES items(id),
    CONSTRAINT INVENTORY_MOVEMENTS_WAREHOUSE_ID_FK FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE TABLE IF NOT EXISTS inventory_balances (
    id               BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id          BIGINT         NOT NULL,
    warehouse_id     BIGINT         NOT NULL,
    quantity         NUMERIC(19, 4) NOT NULL DEFAULT 0,
    transit_quantity NUMERIC(19, 4) NOT NULL DEFAULT 0,
    updated_at       TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    CONSTRAINT INVENTORY_BALANCES_ITEM_WAREHOUSE_UQ UNIQUE (item_id, warehouse_id),
    CONSTRAINT INVENTORY_BALANCES_ITEM_ID_FK        FOREIGN KEY (item_id)      REFERENCES items(id),
    CONSTRAINT INVENTORY_BALANCES_WAREHOUSE_ID_FK   FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

-- ============================================================
-- Transaction reference numbering — per (company, transaction_type)
-- auto-incrementing counter, shared by all transaction types.
-- ============================================================

CREATE TABLE IF NOT EXISTS transaction_sequences (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT      NOT NULL,
    transaction_type VARCHAR(50) NOT NULL,
    last_number      BIGINT      NOT NULL,
    CONSTRAINT TRANSACTION_SEQUENCES_COMPANY_TYPE_UQ UNIQUE (company_id, transaction_type),
    CONSTRAINT TRANSACTION_SEQUENCES_COMPANY_ID_FK    FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- ============================================================
-- Inventory Adjustment — header + lines. Immutable once posted
-- (no update/delete path); posting writes inventory_movements rows
-- and updates inventory_balances.
-- ============================================================

CREATE TABLE IF NOT EXISTS inventory_adjustments (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT      NOT NULL,
    warehouse_id     BIGINT      NOT NULL,
    reference_number VARCHAR(50) NOT NULL,
    sheet_number     VARCHAR(100),
    adjustment_date  TIMESTAMPTZ NOT NULL,
    reason           VARCHAR(255),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(100),
    voided           BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at        TIMESTAMPTZ,
    voided_by        VARCHAR(100),
    loaded           BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT INVENTORY_ADJUSTMENTS_COMPANY_REFERENCE_UQ UNIQUE (company_id, reference_number),
    CONSTRAINT INVENTORY_ADJUSTMENTS_COMPANY_ID_FK   FOREIGN KEY (company_id)   REFERENCES companies(id),
    CONSTRAINT INVENTORY_ADJUSTMENTS_WAREHOUSE_ID_FK FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE TABLE IF NOT EXISTS inventory_adjustment_lines (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adjustment_id   BIGINT         NOT NULL,
    item_id         BIGINT         NOT NULL,
    quantity        NUMERIC(19, 4) NOT NULL,
    line_number     INTEGER        NOT NULL,
    quantity_loaded NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT INVENTORY_ADJUSTMENT_LINES_ADJUSTMENT_ID_FK FOREIGN KEY (adjustment_id) REFERENCES inventory_adjustments(id) ON DELETE CASCADE,
    CONSTRAINT INVENTORY_ADJUSTMENT_LINES_ITEM_ID_FK       FOREIGN KEY (item_id)       REFERENCES items(id)
);

-- ============================================================
-- Purchase Orders — Supplier is the counterparty; Warehouse is the destination.
-- Creating a PO posts a Transit Quantity increase (goods on order, not yet received);
-- voiding reverses it. See docs/TRANSACTIONS.md "Purchase Order" / "Voiding".
-- ============================================================

CREATE TABLE IF NOT EXISTS purchase_orders (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT      NOT NULL,
    warehouse_id     BIGINT      NOT NULL,
    supplier_id      BIGINT      NOT NULL,
    reference_number VARCHAR(50) NOT NULL,
    sheet_number     VARCHAR(100),
    order_date       TIMESTAMPTZ NOT NULL,
    remarks          VARCHAR(255),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(100),
    voided           BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at        TIMESTAMPTZ,
    voided_by        VARCHAR(100),
    loaded           BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT PURCHASE_ORDERS_COMPANY_REFERENCE_UQ UNIQUE (company_id, reference_number),
    CONSTRAINT PURCHASE_ORDERS_COMPANY_ID_FK   FOREIGN KEY (company_id)   REFERENCES companies(id),
    CONSTRAINT PURCHASE_ORDERS_WAREHOUSE_ID_FK FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT PURCHASE_ORDERS_SUPPLIER_ID_FK  FOREIGN KEY (supplier_id) REFERENCES suppliers(id)
);

CREATE TABLE IF NOT EXISTS purchase_order_lines (
    id                BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id BIGINT         NOT NULL,
    item_id           BIGINT         NOT NULL,
    quantity          NUMERIC(19, 4) NOT NULL,
    line_number       INTEGER        NOT NULL,
    cost_price        NUMERIC(19, 4) NOT NULL DEFAULT 0,
    quantity_loaded   NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT PURCHASE_ORDER_LINES_PURCHASE_ORDER_ID_FK FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
    CONSTRAINT PURCHASE_ORDER_LINES_ITEM_ID_FK           FOREIGN KEY (item_id)           REFERENCES items(id)
);

-- ============================================================
-- Purchase Invoices — Supplier is the counterparty. Optionally based on a Purchase Order
-- (loaded in full, 1:1 — see PURCHASE_INVOICES_PURCHASE_ORDER_UQ), otherwise "Direct" mode
-- posts its own Transit Quantity increase, same as Purchase Order does.
-- See docs/TRANSACTIONS.md "Purchase Invoice" / "Voiding".
-- ============================================================

CREATE TABLE IF NOT EXISTS purchase_invoices (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          BIGINT      NOT NULL,
    warehouse_id        BIGINT      NOT NULL,
    supplier_id         BIGINT      NOT NULL,
    purchase_order_id   BIGINT,
    reference_number    VARCHAR(50) NOT NULL,
    sheet_number        VARCHAR(100),
    invoice_date        TIMESTAMPTZ NOT NULL,
    remarks             VARCHAR(255),
    discount_percentage NUMERIC(5, 2) NOT NULL DEFAULT 0,
    payment_status      VARCHAR(20) NOT NULL DEFAULT 'UNPAID',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(100),
    voided              BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at           TIMESTAMPTZ,
    voided_by           VARCHAR(100),
    loaded              BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT PURCHASE_INVOICES_COMPANY_REFERENCE_UQ UNIQUE (company_id, reference_number),
    CONSTRAINT PURCHASE_INVOICES_PURCHASE_ORDER_UQ     UNIQUE (purchase_order_id),
    CONSTRAINT PURCHASE_INVOICES_COMPANY_ID_FK        FOREIGN KEY (company_id)        REFERENCES companies(id),
    CONSTRAINT PURCHASE_INVOICES_WAREHOUSE_ID_FK      FOREIGN KEY (warehouse_id)      REFERENCES warehouses(id),
    CONSTRAINT PURCHASE_INVOICES_SUPPLIER_ID_FK       FOREIGN KEY (supplier_id)       REFERENCES suppliers(id),
    CONSTRAINT PURCHASE_INVOICES_PURCHASE_ORDER_ID_FK FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id)
);

CREATE TABLE IF NOT EXISTS purchase_invoice_lines (
    id                     BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_id    BIGINT         NOT NULL,
    item_id                BIGINT         NOT NULL,
    purchase_order_line_id BIGINT,
    quantity               NUMERIC(19, 4) NOT NULL,
    line_number            INTEGER        NOT NULL,
    cost_price             NUMERIC(19, 4) NOT NULL DEFAULT 0,
    discount_percentage    NUMERIC(5, 2)  NOT NULL DEFAULT 0,
    quantity_loaded        NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT PURCHASE_INVOICE_LINES_PURCHASE_INVOICE_ID_FK    FOREIGN KEY (purchase_invoice_id)    REFERENCES purchase_invoices(id) ON DELETE CASCADE,
    CONSTRAINT PURCHASE_INVOICE_LINES_ITEM_ID_FK                FOREIGN KEY (item_id)                REFERENCES items(id),
    CONSTRAINT PURCHASE_INVOICE_LINES_PURCHASE_ORDER_LINE_ID_FK FOREIGN KEY (purchase_order_line_id) REFERENCES purchase_order_lines(id)
);

CREATE TABLE IF NOT EXISTS purchase_invoice_fees (
    id                   BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_invoice_id  BIGINT         NOT NULL,
    description          VARCHAR(255)   NOT NULL,
    amount               NUMERIC(19, 4) NOT NULL,
    CONSTRAINT PURCHASE_INVOICE_FEES_PURCHASE_INVOICE_ID_FK FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoices(id) ON DELETE CASCADE
);

-- ============================================================
-- Purchase Receives — Supplier is the counterparty (copied from the source). Posted against the
-- outstanding intransit quantity of either a Purchase Order or a Direct-mode Purchase Invoice
-- (exactly one of purchase_order_id / purchase_invoice_id is set, enforced in the service layer,
-- not by a DB constraint, matching this codebase's existing convention). No unique constraint on
-- either FK: a source can be received across multiple partial Purchase Receives.
-- Posting deducts Transit Quantity and adds to main Quantity; voiding reverses it.
-- See docs/TRANSACTIONS.md "Purchase Receive" / "Voiding".
-- ============================================================

CREATE TABLE IF NOT EXISTS purchase_receives (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          BIGINT      NOT NULL,
    warehouse_id        BIGINT      NOT NULL,
    supplier_id         BIGINT      NOT NULL,
    purchase_order_id   BIGINT,
    purchase_invoice_id BIGINT,
    reference_number    VARCHAR(50) NOT NULL,
    sheet_number        VARCHAR(100),
    receipt_date        TIMESTAMPTZ NOT NULL,
    remarks             VARCHAR(255),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(100),
    voided              BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at           TIMESTAMPTZ,
    voided_by           VARCHAR(100),
    loaded              BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT PURCHASE_RECEIVES_COMPANY_REFERENCE_UQ  UNIQUE (company_id, reference_number),
    CONSTRAINT PURCHASE_RECEIVES_COMPANY_ID_FK         FOREIGN KEY (company_id)          REFERENCES companies(id),
    CONSTRAINT PURCHASE_RECEIVES_WAREHOUSE_ID_FK       FOREIGN KEY (warehouse_id)        REFERENCES warehouses(id),
    CONSTRAINT PURCHASE_RECEIVES_SUPPLIER_ID_FK        FOREIGN KEY (supplier_id)         REFERENCES suppliers(id),
    CONSTRAINT PURCHASE_RECEIVES_PURCHASE_ORDER_ID_FK  FOREIGN KEY (purchase_order_id)   REFERENCES purchase_orders(id),
    CONSTRAINT PURCHASE_RECEIVES_PURCHASE_INVOICE_ID_FK FOREIGN KEY (purchase_invoice_id) REFERENCES purchase_invoices(id)
);

CREATE TABLE IF NOT EXISTS purchase_receive_lines (
    id                      BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_receive_id     BIGINT         NOT NULL,
    item_id                 BIGINT         NOT NULL,
    purchase_order_line_id  BIGINT,
    purchase_invoice_line_id BIGINT,
    quantity                NUMERIC(19, 4) NOT NULL,
    line_number             INTEGER        NOT NULL,
    quantity_loaded         NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT PURCHASE_RECEIVE_LINES_PURCHASE_RECEIVE_ID_FK      FOREIGN KEY (purchase_receive_id)      REFERENCES purchase_receives(id) ON DELETE CASCADE,
    CONSTRAINT PURCHASE_RECEIVE_LINES_ITEM_ID_FK                  FOREIGN KEY (item_id)                  REFERENCES items(id),
    CONSTRAINT PURCHASE_RECEIVE_LINES_PURCHASE_ORDER_LINE_ID_FK   FOREIGN KEY (purchase_order_line_id)   REFERENCES purchase_order_lines(id),
    CONSTRAINT PURCHASE_RECEIVE_LINES_PURCHASE_INVOICE_LINE_ID_FK FOREIGN KEY (purchase_invoice_line_id) REFERENCES purchase_invoice_lines(id)
);

-- ============================================================
-- Delivery Receipts — deliver items to a customer out of the company's main
-- warehouse; for an OUTLET also posts in-transit stock in the outlet's warehouse.
-- ============================================================

CREATE TABLE IF NOT EXISTS delivery_receipts (
    id                       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               BIGINT      NOT NULL,
    customer_id              BIGINT      NOT NULL,
    warehouse_id             BIGINT      NOT NULL,
    destination_warehouse_id BIGINT,
    reference_number         VARCHAR(50) NOT NULL,
    sheet_number             VARCHAR(100),
    delivery_date            TIMESTAMPTZ NOT NULL,
    remarks                  VARCHAR(255),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by               VARCHAR(100),
    voided                   BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at                TIMESTAMPTZ,
    voided_by                VARCHAR(100),
    loaded                   BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT DELIVERY_RECEIPTS_COMPANY_REFERENCE_UQ         UNIQUE (company_id, reference_number),
    CONSTRAINT DELIVERY_RECEIPTS_COMPANY_ID_FK                FOREIGN KEY (company_id)               REFERENCES companies(id),
    CONSTRAINT DELIVERY_RECEIPTS_CUSTOMER_ID_FK               FOREIGN KEY (customer_id)              REFERENCES customers(id),
    CONSTRAINT DELIVERY_RECEIPTS_WAREHOUSE_ID_FK              FOREIGN KEY (warehouse_id)             REFERENCES warehouses(id),
    CONSTRAINT DELIVERY_RECEIPTS_DESTINATION_WAREHOUSE_ID_FK  FOREIGN KEY (destination_warehouse_id) REFERENCES warehouses(id)
);

CREATE TABLE IF NOT EXISTS delivery_receipt_lines (
    id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_receipt_id BIGINT         NOT NULL,
    item_id             BIGINT         NOT NULL,
    quantity            NUMERIC(19, 4) NOT NULL,
    unit_price          NUMERIC(19, 4) NOT NULL DEFAULT 0,
    line_number         INTEGER        NOT NULL,
    quantity_loaded     NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT DELIVERY_RECEIPT_LINES_DELIVERY_RECEIPT_ID_FK FOREIGN KEY (delivery_receipt_id) REFERENCES delivery_receipts(id) ON DELETE CASCADE,
    CONSTRAINT DELIVERY_RECEIPT_LINES_ITEM_ID_FK             FOREIGN KEY (item_id)             REFERENCES items(id)
);

-- ============================================================
-- Outlet Receives — accept an outlet Delivery Receipt's in-transit stock
-- into the outlet warehouse's on-hand quantity (partially or in full).
-- ============================================================

CREATE TABLE IF NOT EXISTS outlet_receives (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id          BIGINT      NOT NULL,
    delivery_receipt_id BIGINT      NOT NULL,
    customer_id         BIGINT      NOT NULL,
    warehouse_id        BIGINT      NOT NULL,
    reference_number    VARCHAR(50) NOT NULL,
    sheet_number        VARCHAR(100),
    receipt_date        TIMESTAMPTZ NOT NULL,
    remarks             VARCHAR(255),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(100),
    voided              BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at           TIMESTAMPTZ,
    voided_by           VARCHAR(100),
    loaded              BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT OUTLET_RECEIVES_COMPANY_REFERENCE_UQ   UNIQUE (company_id, reference_number),
    CONSTRAINT OUTLET_RECEIVES_COMPANY_ID_FK          FOREIGN KEY (company_id)          REFERENCES companies(id),
    CONSTRAINT OUTLET_RECEIVES_DELIVERY_RECEIPT_ID_FK FOREIGN KEY (delivery_receipt_id) REFERENCES delivery_receipts(id),
    CONSTRAINT OUTLET_RECEIVES_CUSTOMER_ID_FK         FOREIGN KEY (customer_id)         REFERENCES customers(id),
    CONSTRAINT OUTLET_RECEIVES_WAREHOUSE_ID_FK        FOREIGN KEY (warehouse_id)        REFERENCES warehouses(id)
);

CREATE TABLE IF NOT EXISTS outlet_receive_lines (
    id                       BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet_receive_id        BIGINT         NOT NULL,
    item_id                  BIGINT         NOT NULL,
    delivery_receipt_line_id BIGINT         NOT NULL,
    quantity                 NUMERIC(19, 4) NOT NULL,
    line_number              INTEGER        NOT NULL,
    quantity_loaded          NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT OUTLET_RECEIVE_LINES_OUTLET_RECEIVE_ID_FK        FOREIGN KEY (outlet_receive_id)        REFERENCES outlet_receives(id) ON DELETE CASCADE,
    CONSTRAINT OUTLET_RECEIVE_LINES_ITEM_ID_FK                  FOREIGN KEY (item_id)                  REFERENCES items(id),
    CONSTRAINT OUTLET_RECEIVE_LINES_DELIVERY_RECEIPT_LINE_ID_FK FOREIGN KEY (delivery_receipt_line_id) REFERENCES delivery_receipt_lines(id)
);

-- ============================================================
-- Outlet Delivery Receipts (ODR) — an outlet's sales to (untracked) end
-- customers, deducting on-hand stock from the outlet's own warehouse.
-- The agent (an employee tagged AGENT) earns the sale's commission.
-- ============================================================

CREATE TABLE IF NOT EXISTS outlet_delivery_receipts (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT      NOT NULL,
    customer_id      BIGINT      NOT NULL,
    warehouse_id     BIGINT      NOT NULL,
    agent_id         BIGINT      NOT NULL,
    reference_number VARCHAR(50) NOT NULL,
    sheet_number     VARCHAR(100),
    delivery_date    TIMESTAMPTZ NOT NULL,
    remarks          VARCHAR(255),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(100),
    voided           BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at        TIMESTAMPTZ,
    voided_by        VARCHAR(100),
    loaded           BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT OUTLET_DELIVERY_RECEIPTS_COMPANY_REFERENCE_UQ UNIQUE (company_id, reference_number),
    CONSTRAINT OUTLET_DELIVERY_RECEIPTS_COMPANY_ID_FK        FOREIGN KEY (company_id)   REFERENCES companies(id),
    CONSTRAINT OUTLET_DELIVERY_RECEIPTS_CUSTOMER_ID_FK       FOREIGN KEY (customer_id)  REFERENCES customers(id),
    CONSTRAINT OUTLET_DELIVERY_RECEIPTS_WAREHOUSE_ID_FK      FOREIGN KEY (warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT OUTLET_DELIVERY_RECEIPTS_AGENT_ID_FK          FOREIGN KEY (agent_id)     REFERENCES employees(id)
);

CREATE TABLE IF NOT EXISTS outlet_delivery_receipt_lines (
    id                         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet_delivery_receipt_id BIGINT         NOT NULL,
    item_id                    BIGINT         NOT NULL,
    quantity                   NUMERIC(19, 4) NOT NULL,
    unit_price                 NUMERIC(19, 4) NOT NULL DEFAULT 0,
    line_number                INTEGER        NOT NULL,
    quantity_loaded            NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT OUTLET_DELIVERY_RECEIPT_LINES_OUTLET_DELIVERY_RECEIPT_ID_FK FOREIGN KEY (outlet_delivery_receipt_id) REFERENCES outlet_delivery_receipts(id) ON DELETE CASCADE,
    CONSTRAINT OUTLET_DELIVERY_RECEIPT_LINES_ITEM_ID_FK                    FOREIGN KEY (item_id)                    REFERENCES items(id)
);

-- ============================================================
-- Outlet Delivery Returns — take items sold on an ODR back into the outlet
-- warehouse's on-hand stock (partially or in full).
-- ============================================================

CREATE TABLE IF NOT EXISTS outlet_delivery_returns (
    id                         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id                 BIGINT      NOT NULL,
    outlet_delivery_receipt_id BIGINT      NOT NULL,
    customer_id                BIGINT      NOT NULL,
    warehouse_id               BIGINT      NOT NULL,
    agent_id                   BIGINT      NOT NULL,
    reference_number           VARCHAR(50) NOT NULL,
    sheet_number               VARCHAR(100),
    return_date                TIMESTAMPTZ NOT NULL,
    remarks                    VARCHAR(255),
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by                 VARCHAR(100),
    voided                     BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at                  TIMESTAMPTZ,
    voided_by                  VARCHAR(100),
    loaded                     BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT OUTLET_DELIVERY_RETURNS_COMPANY_REFERENCE_UQ          UNIQUE (company_id, reference_number),
    CONSTRAINT OUTLET_DELIVERY_RETURNS_COMPANY_ID_FK                 FOREIGN KEY (company_id)                 REFERENCES companies(id),
    CONSTRAINT OUTLET_DELIVERY_RETURNS_OUTLET_DELIVERY_RECEIPT_ID_FK FOREIGN KEY (outlet_delivery_receipt_id) REFERENCES outlet_delivery_receipts(id),
    CONSTRAINT OUTLET_DELIVERY_RETURNS_CUSTOMER_ID_FK                FOREIGN KEY (customer_id)                REFERENCES customers(id),
    CONSTRAINT OUTLET_DELIVERY_RETURNS_WAREHOUSE_ID_FK               FOREIGN KEY (warehouse_id)               REFERENCES warehouses(id),
    CONSTRAINT OUTLET_DELIVERY_RETURNS_AGENT_ID_FK                   FOREIGN KEY (agent_id)                   REFERENCES employees(id)
);

CREATE TABLE IF NOT EXISTS outlet_delivery_return_lines (
    id                              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet_delivery_return_id       BIGINT         NOT NULL,
    item_id                         BIGINT         NOT NULL,
    outlet_delivery_receipt_line_id BIGINT         NOT NULL,
    quantity                        NUMERIC(19, 4) NOT NULL,
    unit_price                      NUMERIC(19, 4) NOT NULL DEFAULT 0,
    line_number                     INTEGER        NOT NULL,
    quantity_loaded                 NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT OUTLET_DELIVERY_RETURN_LINES_OUTLET_DELIVERY_RETURN_ID_FK       FOREIGN KEY (outlet_delivery_return_id)       REFERENCES outlet_delivery_returns(id) ON DELETE CASCADE,
    CONSTRAINT OUTLET_DELIVERY_RETURN_LINES_ITEM_ID_FK                         FOREIGN KEY (item_id)                         REFERENCES items(id),
    CONSTRAINT OUTLET_DELIVERY_RETURN_LINES_OUTLET_DELIVERY_RECEIPT_LINE_ID_FK FOREIGN KEY (outlet_delivery_receipt_line_id) REFERENCES outlet_delivery_receipt_lines(id)
);

-- ============================================================
-- Document Templates — printable document layouts. `layout` is an opaque
-- JSON blob owned entirely by the frontend designer; the backend never
-- inspects its contents.
-- ============================================================

CREATE TABLE IF NOT EXISTS document_templates (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    BIGINT       NOT NULL,
    document_type VARCHAR(50)  NOT NULL,
    name          VARCHAR(255) NOT NULL,
    layout        TEXT         NOT NULL,
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100),
    CONSTRAINT DOCUMENT_TEMPLATES_COMPANY_ID_FK FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- ============================================================
-- Transaction Actions & History — see docs/TRANSACTION_ACTIONS.md.
-- transaction_action_definitions: company-configured actions per transaction type.
-- transaction_events: append-only history (CREATED / VOIDED / ACTION).
-- ============================================================

CREATE TABLE IF NOT EXISTS transaction_action_definitions (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT       NOT NULL,
    transaction_type VARCHAR(50)  NOT NULL,
    code             VARCHAR(50)  NOT NULL,
    name             VARCHAR(255) NOT NULL,
    sort_order       INTEGER      NOT NULL DEFAULT 0,
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100),
    CONSTRAINT TXN_ACTION_DEF_COMPANY_TYPE_CODE_UQ UNIQUE (company_id, transaction_type, code),
    CONSTRAINT TXN_ACTION_DEFS_COMPANY_ID_FK       FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS transaction_action_definition_prerequisites (
    action_definition_id BIGINT NOT NULL,
    prerequisite_id      BIGINT NOT NULL,
    PRIMARY KEY (action_definition_id, prerequisite_id),
    CONSTRAINT TXN_ACTION_DEF_PREREQS_DEF_ID_FK    FOREIGN KEY (action_definition_id) REFERENCES transaction_action_definitions(id) ON DELETE CASCADE,
    CONSTRAINT TXN_ACTION_DEF_PREREQS_PREREQ_ID_FK FOREIGN KEY (prerequisite_id)      REFERENCES transaction_action_definitions(id)
);

CREATE TABLE IF NOT EXISTS transaction_action_definition_roles (
    action_definition_id BIGINT NOT NULL,
    role_id              BIGINT NOT NULL,
    PRIMARY KEY (action_definition_id, role_id),
    CONSTRAINT TXN_ACTION_DEF_ROLES_DEF_ID_FK  FOREIGN KEY (action_definition_id) REFERENCES transaction_action_definitions(id) ON DELETE CASCADE,
    CONSTRAINT TXN_ACTION_DEF_ROLES_ROLE_ID_FK FOREIGN KEY (role_id)              REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS transaction_events (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id           BIGINT       NOT NULL,
    transaction_type     VARCHAR(50)  NOT NULL,
    transaction_id       BIGINT       NOT NULL,
    reference_number     VARCHAR(50)  NOT NULL,
    event_type           VARCHAR(20)  NOT NULL,
    action_definition_id BIGINT,
    action_code          VARCHAR(50),
    action_name          VARCHAR(255),
    performed_by         VARCHAR(100) NOT NULL,
    performed_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    remarks              VARCHAR(255),
    -- NULL action_definition_id (CREATED/VOIDED) is distinct, so this only constrains ACTION rows.
    CONSTRAINT TXN_EVENT_ACTION_USER_UQ           UNIQUE (transaction_type, transaction_id, action_definition_id, performed_by),
    CONSTRAINT TXN_EVENTS_COMPANY_ID_FK           FOREIGN KEY (company_id)           REFERENCES companies(id),
    CONSTRAINT TXN_EVENTS_ACTION_DEFINITION_ID_FK FOREIGN KEY (action_definition_id) REFERENCES transaction_action_definitions(id)
);

CREATE INDEX IF NOT EXISTS TXN_EVENTS_TRANSACTION_IDX ON transaction_events (transaction_type, transaction_id, performed_at);

-- ============================================================
-- User Preferences — a user's own UI settings (e.g. saved list column
-- layouts), keyed by a frontend-chosen string. `value` is opaque JSON
-- owned by the frontend. Per user, not per company.
-- ============================================================

CREATE TABLE IF NOT EXISTS user_preferences (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    pref_key   VARCHAR(100) NOT NULL,
    value      TEXT         NOT NULL,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT USER_PREFERENCES_USER_KEY_UQ UNIQUE (user_id, pref_key),
    CONSTRAINT USER_PREFERENCES_USER_ID_FK  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- Seed data
-- The application's DataInitializer also runs these upserts on
-- every startup, so both paths are safe to run concurrently.
-- ============================================================

INSERT INTO permissions (name, description) VALUES
    ('MANAGE_SYSTEM',        'Security - System Manage'),
    ('VIEW_USER',            'Security - User View'),
    ('CREATE_USER',          'Security - User Create'),
    ('UPDATE_USER',          'Security - User Update'),
    ('DELETE_USER',          'Security - User Delete'),
    ('RESET_USER_PASSWORD',  'Security - User Reset Password'),
    ('VIEW_ROLE',            'Security - Role View'),
    ('CREATE_ROLE',          'Security - Role Create'),
    ('UPDATE_ROLE',          'Security - Role Update'),
    ('DELETE_ROLE',          'Security - Role Delete'),
    ('VIEW_ITEM',            'Maintenance - Item View'),
    ('CREATE_ITEM',          'Maintenance - Item Create'),
    ('UPDATE_ITEM',          'Maintenance - Item Update'),
    ('DELETE_ITEM',          'Maintenance - Item Delete'),
    ('VIEW_COST_PRICE',      'Maintenance - Item Cost Price View'),
    ('VIEW_BRAND',           'Maintenance - Brand View'),
    ('CREATE_BRAND',         'Maintenance - Brand Create'),
    ('UPDATE_BRAND',         'Maintenance - Brand Update'),
    ('DELETE_BRAND',         'Maintenance - Brand Delete'),
    ('VIEW_ITEM_CATEGORY',   'Maintenance - Item Category View'),
    ('CREATE_ITEM_CATEGORY', 'Maintenance - Item Category Create'),
    ('UPDATE_ITEM_CATEGORY', 'Maintenance - Item Category Update'),
    ('DELETE_ITEM_CATEGORY', 'Maintenance - Item Category Delete'),
    ('VIEW_ITEM_GROUP',      'Maintenance - Item Group View'),
    ('CREATE_ITEM_GROUP',    'Maintenance - Item Group Create'),
    ('UPDATE_ITEM_GROUP',    'Maintenance - Item Group Update'),
    ('DELETE_ITEM_GROUP',    'Maintenance - Item Group Delete'),
    ('VIEW_WAREHOUSE',       'Maintenance - Warehouse View'),
    ('CREATE_WAREHOUSE',     'Maintenance - Warehouse Create'),
    ('UPDATE_WAREHOUSE',     'Maintenance - Warehouse Update'),
    ('DELETE_WAREHOUSE',     'Maintenance - Warehouse Delete'),
    ('VIEW_EMPLOYEE',        'HR - Employee View'),
    ('CREATE_EMPLOYEE',      'HR - Employee Create'),
    ('UPDATE_EMPLOYEE',      'HR - Employee Update'),
    ('DELETE_EMPLOYEE',      'HR - Employee Delete'),
    ('VIEW_SUPPLIER',              'Maintenance - Supplier View'),
    ('CREATE_SUPPLIER',            'Maintenance - Supplier Create'),
    ('UPDATE_SUPPLIER',            'Maintenance - Supplier Update'),
    ('DELETE_SUPPLIER',            'Maintenance - Supplier Delete'),
    ('VIEW_CUSTOMER',              'Maintenance - Customer View'),
    ('CREATE_CUSTOMER',            'Maintenance - Customer Create'),
    ('UPDATE_CUSTOMER',            'Maintenance - Customer Update'),
    ('DELETE_CUSTOMER',            'Maintenance - Customer Delete'),
    ('VIEW_INVENTORY_ADJUSTMENT',  'Inventory - Adjustment View'),
    ('CREATE_INVENTORY_ADJUSTMENT','Inventory - Adjustment Create'),
    ('VOID_INVENTORY_ADJUSTMENT',  'Inventory - Adjustment Void'),
    ('VIEW_PURCHASE_ORDER',        'Purchases - Purchase Order View'),
    ('CREATE_PURCHASE_ORDER',      'Purchases - Purchase Order Create'),
    ('VOID_PURCHASE_ORDER',        'Purchases - Purchase Order Void'),
    ('VIEW_PURCHASE_INVOICE',      'Purchases - Purchase Invoice View'),
    ('CREATE_PURCHASE_INVOICE',    'Purchases - Purchase Invoice Create'),
    ('VOID_PURCHASE_INVOICE',      'Purchases - Purchase Invoice Void'),
    ('VIEW_PURCHASE_RECEIVE',      'Purchases - Purchase Receive View'),
    ('CREATE_PURCHASE_RECEIVE',    'Purchases - Purchase Receive Create'),
    ('VOID_PURCHASE_RECEIVE',      'Purchases - Purchase Receive Void'),
    ('VIEW_DELIVERY_RECEIPT',      'Sales - Delivery Receipt View'),
    ('CREATE_DELIVERY_RECEIPT',    'Sales - Delivery Receipt Create'),
    ('VOID_DELIVERY_RECEIPT',      'Sales - Delivery Receipt Void'),
    ('VIEW_OUTLET_RECEIVE',        'Inventory - Outlet Receive View'),
    ('CREATE_OUTLET_RECEIVE',      'Inventory - Outlet Receive Create'),
    ('VOID_OUTLET_RECEIVE',        'Inventory - Outlet Receive Void'),
    ('VIEW_OUTLET_DELIVERY_RECEIPT',   'Sales - Outlet Delivery Receipt View'),
    ('CREATE_OUTLET_DELIVERY_RECEIPT', 'Sales - Outlet Delivery Receipt Create'),
    ('VOID_OUTLET_DELIVERY_RECEIPT',   'Sales - Outlet Delivery Receipt Void'),
    ('VIEW_OUTLET_DELIVERY_RETURN',    'Sales - Outlet Delivery Return View'),
    ('CREATE_OUTLET_DELIVERY_RETURN',  'Sales - Outlet Delivery Return Create'),
    ('VOID_OUTLET_DELIVERY_RETURN',    'Sales - Outlet Delivery Return Void'),
    ('VIEW_INVENTORY_REPORT',      'Inventory - Report View'),
    ('MANAGE_DOCUMENT_TEMPLATES',  'Document Templates - Manage (design + print)'),
    ('MANAGE_TRANSACTION_ACTIONS', 'Configuration - Transaction Actions Manage')
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

INSERT INTO roles (name, display_name) VALUES
    ('ADMIN',        'Administrator'),
    ('SYSTEM_ADMIN', 'System Administrator'),
    ('SUPER_ADMIN',  'Super Administrator')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON true
WHERE (r.name = 'SYSTEM_ADMIN' AND p.name IN (
    'VIEW_USER', 'CREATE_USER', 'VIEW_ROLE',
    'VIEW_ITEM', 'CREATE_ITEM', 'UPDATE_ITEM',
    'VIEW_BRAND', 'CREATE_BRAND', 'UPDATE_BRAND',
    'VIEW_ITEM_CATEGORY', 'CREATE_ITEM_CATEGORY', 'UPDATE_ITEM_CATEGORY',
    'VIEW_ITEM_GROUP', 'CREATE_ITEM_GROUP', 'UPDATE_ITEM_GROUP',
    'VIEW_WAREHOUSE', 'CREATE_WAREHOUSE', 'UPDATE_WAREHOUSE',
    'VIEW_EMPLOYEE', 'CREATE_EMPLOYEE', 'UPDATE_EMPLOYEE',
    'VIEW_SUPPLIER', 'CREATE_SUPPLIER', 'UPDATE_SUPPLIER',
    'VIEW_CUSTOMER', 'CREATE_CUSTOMER', 'UPDATE_CUSTOMER',
    'VIEW_INVENTORY_ADJUSTMENT', 'CREATE_INVENTORY_ADJUSTMENT', 'VOID_INVENTORY_ADJUSTMENT',
    'VIEW_PURCHASE_ORDER', 'CREATE_PURCHASE_ORDER', 'VOID_PURCHASE_ORDER',
    'VIEW_PURCHASE_INVOICE', 'CREATE_PURCHASE_INVOICE', 'VOID_PURCHASE_INVOICE',
    'VIEW_PURCHASE_RECEIVE', 'CREATE_PURCHASE_RECEIVE', 'VOID_PURCHASE_RECEIVE',
    'VIEW_DELIVERY_RECEIPT', 'CREATE_DELIVERY_RECEIPT', 'VOID_DELIVERY_RECEIPT',
    'VIEW_OUTLET_RECEIVE', 'CREATE_OUTLET_RECEIVE', 'VOID_OUTLET_RECEIVE',
    'VIEW_OUTLET_DELIVERY_RECEIPT', 'CREATE_OUTLET_DELIVERY_RECEIPT', 'VOID_OUTLET_DELIVERY_RECEIPT',
    'VIEW_OUTLET_DELIVERY_RETURN', 'CREATE_OUTLET_DELIVERY_RETURN', 'VOID_OUTLET_DELIVERY_RETURN',
    'VIEW_INVENTORY_REPORT', 'MANAGE_DOCUMENT_TEMPLATES', 'MANAGE_TRANSACTION_ACTIONS'
))
OR (r.name = 'SUPER_ADMIN' AND p.name IN (
    'MANAGE_SYSTEM',
    'VIEW_USER', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER', 'RESET_USER_PASSWORD',
    'VIEW_ROLE', 'CREATE_ROLE', 'UPDATE_ROLE', 'DELETE_ROLE',
    'VIEW_ITEM', 'CREATE_ITEM', 'UPDATE_ITEM', 'DELETE_ITEM', 'VIEW_COST_PRICE',
    'VIEW_BRAND', 'CREATE_BRAND', 'UPDATE_BRAND', 'DELETE_BRAND',
    'VIEW_ITEM_CATEGORY', 'CREATE_ITEM_CATEGORY', 'UPDATE_ITEM_CATEGORY', 'DELETE_ITEM_CATEGORY',
    'VIEW_ITEM_GROUP', 'CREATE_ITEM_GROUP', 'UPDATE_ITEM_GROUP', 'DELETE_ITEM_GROUP',
    'VIEW_WAREHOUSE', 'CREATE_WAREHOUSE', 'UPDATE_WAREHOUSE', 'DELETE_WAREHOUSE',
    'VIEW_EMPLOYEE', 'CREATE_EMPLOYEE', 'UPDATE_EMPLOYEE', 'DELETE_EMPLOYEE',
    'VIEW_SUPPLIER', 'CREATE_SUPPLIER', 'UPDATE_SUPPLIER', 'DELETE_SUPPLIER',
    'VIEW_CUSTOMER', 'CREATE_CUSTOMER', 'UPDATE_CUSTOMER', 'DELETE_CUSTOMER',
    'VIEW_INVENTORY_ADJUSTMENT', 'CREATE_INVENTORY_ADJUSTMENT', 'VOID_INVENTORY_ADJUSTMENT',
    'VIEW_PURCHASE_ORDER', 'CREATE_PURCHASE_ORDER', 'VOID_PURCHASE_ORDER',
    'VIEW_PURCHASE_INVOICE', 'CREATE_PURCHASE_INVOICE', 'VOID_PURCHASE_INVOICE',
    'VIEW_PURCHASE_RECEIVE', 'CREATE_PURCHASE_RECEIVE', 'VOID_PURCHASE_RECEIVE',
    'VIEW_DELIVERY_RECEIPT', 'CREATE_DELIVERY_RECEIPT', 'VOID_DELIVERY_RECEIPT',
    'VIEW_OUTLET_RECEIVE', 'CREATE_OUTLET_RECEIVE', 'VOID_OUTLET_RECEIVE',
    'VIEW_OUTLET_DELIVERY_RECEIPT', 'CREATE_OUTLET_DELIVERY_RECEIPT', 'VOID_OUTLET_DELIVERY_RECEIPT',
    'VIEW_OUTLET_DELIVERY_RETURN', 'CREATE_OUTLET_DELIVERY_RETURN', 'VOID_OUTLET_DELIVERY_RETURN',
    'VIEW_INVENTORY_REPORT', 'MANAGE_DOCUMENT_TEMPLATES', 'MANAGE_TRANSACTION_ACTIONS'
))
ON CONFLICT DO NOTHING;

INSERT INTO companies (name) VALUES ('Norbiz')
ON CONFLICT DO NOTHING;

-- Passwords are hashed at insert time via pgcrypto (BCrypt, cost 10).
-- Change the plaintext values here before running on a new environment.
INSERT INTO users (username, email, password) VALUES
    ('admin',        'admin@norbiz.com',        crypt('change-me-admin',        gen_salt('bf', 10))),
    ('super_admin',  'super.admin@norbiz.com',  crypt('password',  gen_salt('bf', 10))),
    ('system_admin', 'system.admin@norbiz.com', crypt('change-me-system-admin', gen_salt('bf', 10)))
ON CONFLICT (username) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u JOIN roles r ON true
WHERE (u.username = 'admin'        AND r.name = 'ADMIN')
   OR (u.username = 'super_admin'  AND r.name = 'SUPER_ADMIN')
   OR (u.username = 'system_admin' AND r.name = 'SYSTEM_ADMIN')
ON CONFLICT DO NOTHING;

INSERT INTO user_companies (user_id, company_id)
SELECT u.id, c.id FROM users u JOIN companies c ON true
WHERE u.username = 'super_admin' AND c.name = 'Norbiz'
ON CONFLICT DO NOTHING;

-- Transaction origin (NATIVE | MIGRATED | RECONSTRUCTED). Only the legacy migration loader writes anything
-- but NATIVE — see docs/LEGACY_MIGRATION.md.
ALTER TABLE inventory_adjustments    ADD COLUMN IF NOT EXISTS origin VARCHAR(20) NOT NULL DEFAULT 'NATIVE';
ALTER TABLE purchase_orders          ADD COLUMN IF NOT EXISTS origin VARCHAR(20) NOT NULL DEFAULT 'NATIVE';
ALTER TABLE purchase_invoices        ADD COLUMN IF NOT EXISTS origin VARCHAR(20) NOT NULL DEFAULT 'NATIVE';
ALTER TABLE purchase_receives        ADD COLUMN IF NOT EXISTS origin VARCHAR(20) NOT NULL DEFAULT 'NATIVE';
ALTER TABLE delivery_receipts        ADD COLUMN IF NOT EXISTS origin VARCHAR(20) NOT NULL DEFAULT 'NATIVE';
ALTER TABLE outlet_receives          ADD COLUMN IF NOT EXISTS origin VARCHAR(20) NOT NULL DEFAULT 'NATIVE';
ALTER TABLE outlet_delivery_receipts ADD COLUMN IF NOT EXISTS origin VARCHAR(20) NOT NULL DEFAULT 'NATIVE';
ALTER TABLE outlet_delivery_returns  ADD COLUMN IF NOT EXISTS origin VARCHAR(20) NOT NULL DEFAULT 'NATIVE';


-- ============================================================
-- Pull Out Reason / Bill of Materials (master data) and the Stock Transfer, Outlet Pull Out,
-- Pull Out Receive and Assembly transactions — see docs/TRANSACTIONS.md and docs/MASTER_DATA.md.
-- ============================================================
CREATE TABLE IF NOT EXISTS pull_out_reasons (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,
    name       VARCHAR(255) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT PULL_OUT_REASONS_COMPANY_NAME_UQ UNIQUE (company_id, name),
    CONSTRAINT PULL_OUT_REASONS_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id)
);

CREATE TABLE IF NOT EXISTS bills_of_materials (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,
    code       VARCHAR(100) NOT NULL,
    item_id    BIGINT       NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT BILLS_OF_MATERIALS_COMPANY_CODE_UQ UNIQUE (company_id, code),
    CONSTRAINT BILLS_OF_MATERIALS_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT BILLS_OF_MATERIALS_ITEM_ID_FK      FOREIGN KEY (item_id)    REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS bill_of_material_lines (
    id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_of_material_id BIGINT         NOT NULL,
    item_id             BIGINT         NOT NULL,
    quantity            NUMERIC(19, 4) NOT NULL,
    line_number         INTEGER        NOT NULL,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),
    CONSTRAINT BILL_OF_MATERIAL_LINES_BILL_OF_MATERIAL_ID_FK FOREIGN KEY (bill_of_material_id) REFERENCES bills_of_materials(id) ON DELETE CASCADE,
    CONSTRAINT BILL_OF_MATERIAL_LINES_ITEM_ID_FK             FOREIGN KEY (item_id)             REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS stock_transfers (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT      NOT NULL,
    customer_id      BIGINT      NOT NULL,
    warehouse_id     BIGINT      NOT NULL,
    reference_number VARCHAR(50) NOT NULL,
    sheet_number     VARCHAR(100),
    transfer_date    TIMESTAMPTZ NOT NULL,
    remarks          VARCHAR(255),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(100),
    voided           BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at        TIMESTAMPTZ,
    voided_by        VARCHAR(100),
    loaded           BOOLEAN     NOT NULL DEFAULT FALSE,
    origin           VARCHAR(20) NOT NULL DEFAULT 'NATIVE',
    CONSTRAINT STOCK_TRANSFERS_COMPANY_REFERENCE_UQ UNIQUE (company_id, reference_number),
    CONSTRAINT STOCK_TRANSFERS_COMPANY_ID_FK        FOREIGN KEY (company_id)   REFERENCES companies(id),
    CONSTRAINT STOCK_TRANSFERS_CUSTOMER_ID_FK       FOREIGN KEY (customer_id)  REFERENCES customers(id),
    CONSTRAINT STOCK_TRANSFERS_WAREHOUSE_ID_FK      FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE TABLE IF NOT EXISTS stock_transfer_lines (
    id                BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_transfer_id BIGINT         NOT NULL,
    item_id           BIGINT         NOT NULL,
    quantity          NUMERIC(19, 4) NOT NULL,
    unit_price        NUMERIC(19, 4) NOT NULL DEFAULT 0,
    line_number       INTEGER        NOT NULL,
    quantity_loaded   NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT STOCK_TRANSFER_LINES_STOCK_TRANSFER_ID_FK FOREIGN KEY (stock_transfer_id) REFERENCES stock_transfers(id) ON DELETE CASCADE,
    CONSTRAINT STOCK_TRANSFER_LINES_ITEM_ID_FK           FOREIGN KEY (item_id)           REFERENCES items(id)
);

-- A Delivery Receipt may deliver one Stock Transfer in full.
ALTER TABLE delivery_receipts ADD COLUMN IF NOT EXISTS stock_transfer_id BIGINT;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'delivery_receipts_stock_transfer_id_fk') THEN
        ALTER TABLE delivery_receipts ADD CONSTRAINT DELIVERY_RECEIPTS_STOCK_TRANSFER_ID_FK FOREIGN KEY (stock_transfer_id) REFERENCES stock_transfers(id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS outlet_pull_outs (
    id                       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id               BIGINT      NOT NULL,
    customer_id              BIGINT      NOT NULL,
    warehouse_id             BIGINT      NOT NULL,
    destination_warehouse_id BIGINT      NOT NULL,
    pull_out_reason_id       BIGINT,
    reference_number         VARCHAR(50) NOT NULL,
    sheet_number             VARCHAR(100),
    pull_out_date            TIMESTAMPTZ NOT NULL,
    remarks          VARCHAR(255),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(100),
    voided           BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at        TIMESTAMPTZ,
    voided_by        VARCHAR(100),
    loaded           BOOLEAN     NOT NULL DEFAULT FALSE,
    origin           VARCHAR(20) NOT NULL DEFAULT 'NATIVE',
    CONSTRAINT OUTLET_PULL_OUTS_COMPANY_REFERENCE_UQ         UNIQUE (company_id, reference_number),
    CONSTRAINT OUTLET_PULL_OUTS_COMPANY_ID_FK                FOREIGN KEY (company_id)               REFERENCES companies(id),
    CONSTRAINT OUTLET_PULL_OUTS_CUSTOMER_ID_FK               FOREIGN KEY (customer_id)              REFERENCES customers(id),
    CONSTRAINT OUTLET_PULL_OUTS_WAREHOUSE_ID_FK              FOREIGN KEY (warehouse_id)             REFERENCES warehouses(id),
    CONSTRAINT OUTLET_PULL_OUTS_DESTINATION_WAREHOUSE_ID_FK  FOREIGN KEY (destination_warehouse_id) REFERENCES warehouses(id),
    CONSTRAINT OUTLET_PULL_OUTS_PULL_OUT_REASON_ID_FK        FOREIGN KEY (pull_out_reason_id)       REFERENCES pull_out_reasons(id)
);

CREATE TABLE IF NOT EXISTS outlet_pull_out_lines (
    id                 BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet_pull_out_id BIGINT         NOT NULL,
    item_id            BIGINT         NOT NULL,
    quantity           NUMERIC(19, 4) NOT NULL,
    unit_price         NUMERIC(19, 4) NOT NULL DEFAULT 0,
    line_number        INTEGER        NOT NULL,
    quantity_loaded    NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT OUTLET_PULL_OUT_LINES_OUTLET_PULL_OUT_ID_FK FOREIGN KEY (outlet_pull_out_id) REFERENCES outlet_pull_outs(id) ON DELETE CASCADE,
    CONSTRAINT OUTLET_PULL_OUT_LINES_ITEM_ID_FK            FOREIGN KEY (item_id)            REFERENCES items(id)
);

CREATE TABLE IF NOT EXISTS pull_out_receives (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id         BIGINT      NOT NULL,
    outlet_pull_out_id BIGINT      NOT NULL,
    customer_id        BIGINT      NOT NULL,
    warehouse_id       BIGINT      NOT NULL,
    reference_number   VARCHAR(50) NOT NULL,
    sheet_number       VARCHAR(100),
    receipt_date       TIMESTAMPTZ NOT NULL,
    remarks          VARCHAR(255),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(100),
    voided           BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at        TIMESTAMPTZ,
    voided_by        VARCHAR(100),
    loaded           BOOLEAN     NOT NULL DEFAULT FALSE,
    origin           VARCHAR(20) NOT NULL DEFAULT 'NATIVE',
    CONSTRAINT PULL_OUT_RECEIVES_COMPANY_REFERENCE_UQ   UNIQUE (company_id, reference_number),
    CONSTRAINT PULL_OUT_RECEIVES_COMPANY_ID_FK          FOREIGN KEY (company_id)         REFERENCES companies(id),
    CONSTRAINT PULL_OUT_RECEIVES_OUTLET_PULL_OUT_ID_FK  FOREIGN KEY (outlet_pull_out_id) REFERENCES outlet_pull_outs(id),
    CONSTRAINT PULL_OUT_RECEIVES_CUSTOMER_ID_FK         FOREIGN KEY (customer_id)        REFERENCES customers(id),
    CONSTRAINT PULL_OUT_RECEIVES_WAREHOUSE_ID_FK        FOREIGN KEY (warehouse_id)       REFERENCES warehouses(id)
);

CREATE TABLE IF NOT EXISTS pull_out_receive_lines (
    id                      BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pull_out_receive_id     BIGINT         NOT NULL,
    item_id                 BIGINT         NOT NULL,
    outlet_pull_out_line_id BIGINT         NOT NULL,
    quantity                NUMERIC(19, 4) NOT NULL,
    line_number             INTEGER        NOT NULL,
    quantity_loaded         NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT PULL_OUT_RECEIVE_LINES_PULL_OUT_RECEIVE_ID_FK     FOREIGN KEY (pull_out_receive_id)     REFERENCES pull_out_receives(id) ON DELETE CASCADE,
    CONSTRAINT PULL_OUT_RECEIVE_LINES_ITEM_ID_FK                 FOREIGN KEY (item_id)                 REFERENCES items(id),
    CONSTRAINT PULL_OUT_RECEIVE_LINES_OUTLET_PULL_OUT_LINE_ID_FK FOREIGN KEY (outlet_pull_out_line_id) REFERENCES outlet_pull_out_lines(id)
);

CREATE TABLE IF NOT EXISTS assemblies (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT      NOT NULL,
    warehouse_id     BIGINT      NOT NULL,
    reference_number VARCHAR(50) NOT NULL,
    sheet_number     VARCHAR(100),
    assembly_date    TIMESTAMPTZ NOT NULL,
    remarks          VARCHAR(255),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(100),
    voided           BOOLEAN     NOT NULL DEFAULT FALSE,
    voided_at        TIMESTAMPTZ,
    voided_by        VARCHAR(100),
    loaded           BOOLEAN     NOT NULL DEFAULT FALSE,
    origin           VARCHAR(20) NOT NULL DEFAULT 'NATIVE',
    CONSTRAINT ASSEMBLIES_COMPANY_REFERENCE_UQ UNIQUE (company_id, reference_number),
    CONSTRAINT ASSEMBLIES_COMPANY_ID_FK        FOREIGN KEY (company_id)   REFERENCES companies(id),
    CONSTRAINT ASSEMBLIES_WAREHOUSE_ID_FK      FOREIGN KEY (warehouse_id) REFERENCES warehouses(id)
);

CREATE TABLE IF NOT EXISTS assembly_lines (
    id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assembly_id         BIGINT         NOT NULL,
    item_id             BIGINT         NOT NULL,
    kind                VARCHAR(20)    NOT NULL, -- OUTPUT | MATERIAL
    bill_of_material_id BIGINT,
    quantity            NUMERIC(19, 4) NOT NULL,
    line_number         INTEGER        NOT NULL,
    quantity_loaded     NUMERIC(19, 4) NOT NULL DEFAULT 0,
    CONSTRAINT ASSEMBLY_LINES_ASSEMBLY_ID_FK         FOREIGN KEY (assembly_id)         REFERENCES assemblies(id) ON DELETE CASCADE,
    CONSTRAINT ASSEMBLY_LINES_ITEM_ID_FK             FOREIGN KEY (item_id)             REFERENCES items(id),
    CONSTRAINT ASSEMBLY_LINES_BILL_OF_MATERIAL_ID_FK FOREIGN KEY (bill_of_material_id) REFERENCES bills_of_materials(id)
);

-- SKU codes may be shared by several items (unique per item only). Databases created before this
-- change still carry the old global constraint, which ddl-auto=update never drops.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'item_skus_sku_code_uq') THEN
        ALTER TABLE item_skus DROP CONSTRAINT item_skus_sku_code_uq;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'item_skus_item_sku_code_uq') THEN
        ALTER TABLE item_skus ADD CONSTRAINT ITEM_SKUS_ITEM_SKU_CODE_UQ UNIQUE (item_id, sku_code);
    END IF;
END $$;

-- SKUs gained their own company (so a SKU may exist without an item) and the legacy price point
-- columns. Databases created before this carry item_id NOT NULL and lack the new columns.
ALTER TABLE item_skus ADD COLUMN IF NOT EXISTS company_id       BIGINT;
ALTER TABLE item_skus ADD COLUMN IF NOT EXISTS item_category_id BIGINT;
ALTER TABLE item_skus ADD COLUMN IF NOT EXISTS brand_id         BIGINT;
ALTER TABLE item_skus ADD COLUMN IF NOT EXISTS price_type       VARCHAR(20);
ALTER TABLE item_skus ADD COLUMN IF NOT EXISTS store_item_code  VARCHAR(100);
ALTER TABLE item_skus ADD COLUMN IF NOT EXISTS barcode          VARCHAR(100);
ALTER TABLE item_skus ADD COLUMN IF NOT EXISTS vendor_part      VARCHAR(100);
ALTER TABLE item_skus ADD COLUMN IF NOT EXISTS rds_description  VARCHAR(255);
ALTER TABLE item_skus ADD COLUMN IF NOT EXISTS active           BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE item_skus ADD COLUMN IF NOT EXISTS rds_sku          BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE item_skus ADD COLUMN IF NOT EXISTS landmark_sku     BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE item_skus s SET company_id = i.company_id FROM items i WHERE i.id = s.item_id AND s.company_id IS NULL;
ALTER TABLE item_skus ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE item_skus ALTER COLUMN item_id DROP NOT NULL;
-- SKUs are looked up by brand, then category, then price.
CREATE INDEX IF NOT EXISTS ITEM_SKUS_BRAND_CATEGORY_PRICE_IX ON item_skus (company_id, brand_id, item_category_id, unit_price);
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'item_skus_company_id_fk') THEN
        ALTER TABLE item_skus ADD CONSTRAINT ITEM_SKUS_COMPANY_ID_FK FOREIGN KEY (company_id) REFERENCES companies(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'item_skus_item_category_id_fk') THEN
        ALTER TABLE item_skus ADD CONSTRAINT ITEM_SKUS_ITEM_CATEGORY_ID_FK FOREIGN KEY (item_category_id) REFERENCES item_categories(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'item_skus_brand_id_fk') THEN
        ALTER TABLE item_skus ADD CONSTRAINT ITEM_SKUS_BRAND_ID_FK FOREIGN KEY (brand_id) REFERENCES brands(id);
    END IF;
END $$;
