-- Database is created automatically via POSTGRES_DB env var.
-- Add any additional initialization here (extensions, schemas, seed data, etc.)

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Add description column to permissions if it doesn't exist (idempotent migration)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'permissions' AND column_name = 'description'
    ) THEN
        ALTER TABLE permissions ADD COLUMN description VARCHAR(255);
    END IF;
END $$;

ALTER DATABASE norbiz SET search_path TO public;

-- ============================================================
-- Multi-tenancy: companies
-- ============================================================

CREATE TABLE IF NOT EXISTS companies (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Tracks which companies a user can access.
-- Regular users belong to one company; super/system admins may span many.
CREATE TABLE IF NOT EXISTS user_companies (
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, company_id)
);

-- ============================================================
-- Items
-- ============================================================

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT        NOT NULL REFERENCES companies(id),
    item_code   VARCHAR(100)  NOT NULL,
    name        VARCHAR(255)  NOT NULL,
    -- Relative path from the application's configured image root
    image_path  VARCHAR(500),
    active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    UNIQUE (company_id, item_code)
);

-- SKU codes — globally unique; one item can have many SKUs
CREATE TABLE IF NOT EXISTS item_skus (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id   BIGINT       NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    sku_code  VARCHAR(100) NOT NULL,
    UNIQUE (sku_code)
);

-- Prices — one row per price type per item
CREATE TABLE IF NOT EXISTS item_prices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id     BIGINT         NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    price_type  VARCHAR(20)    NOT NULL, -- UNIT_PRICE | COST_PRICE | FOCAL_PRICE | MARKDOWN_PRICE
    amount      NUMERIC(19, 4) NOT NULL,
    UNIQUE (item_id, price_type)
);