-- ============================================================
-- Norbiz — full schema for a fresh database
-- Runs once on first container start via Docker POSTGRES_DB init.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

ALTER DATABASE norbiz SET search_path TO public;

-- ============================================================
-- Security
-- ============================================================

CREATE TABLE IF NOT EXISTS permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by  VARCHAR(100),
    updated_by  VARCHAR(100),
    CONSTRAINT PERMISSIONS_NAME_UQ UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    CONSTRAINT ROLES_NAME_UQ UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT ROLE_PERMISSIONS_ROLE_ID_FK       FOREIGN KEY (role_id)       REFERENCES roles(id)       ON DELETE CASCADE,
    CONSTRAINT ROLE_PERMISSIONS_PERMISSION_ID_FK FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(255) NOT NULL,
    display_name VARCHAR(255),
    email        VARCHAR(255) NOT NULL,
    password     VARCHAR(255) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by   VARCHAR(100),
    updated_by   VARCHAR(100),
    CONSTRAINT USERS_USERNAME_UQ UNIQUE (username),
    CONSTRAINT USERS_EMAIL_UQ    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT USER_ROLES_USER_ID_FK FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT USER_ROLES_ROLE_ID_FK FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- ============================================================
-- Multi-tenancy: companies
-- ============================================================

CREATE TABLE IF NOT EXISTS companies (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100)
);

-- Regular users belong to one company; super/system admins may span many.
CREATE TABLE IF NOT EXISTS user_companies (
    user_id    BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, company_id),
    CONSTRAINT USER_COMPANIES_USER_ID_FK    FOREIGN KEY (user_id)    REFERENCES users(id)     ON DELETE CASCADE,
    CONSTRAINT USER_COMPANIES_COMPANY_ID_FK FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

-- ============================================================
-- Item Categories
-- ============================================================

CREATE TABLE IF NOT EXISTS item_categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT ITEM_CATEGORIES_COMPANY_NAME_UQ UNIQUE (company_id, name),
    CONSTRAINT ITEM_CATEGORIES_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- ============================================================
-- Items
-- ============================================================

CREATE TABLE IF NOT EXISTS items (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id       BIGINT       NOT NULL,
    item_category_id BIGINT       NOT NULL,
    item_code        VARCHAR(100) NOT NULL,
    name             VARCHAR(255) NOT NULL,
    image_path       VARCHAR(500),
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by       VARCHAR(100),
    updated_by       VARCHAR(100),
    CONSTRAINT ITEMS_COMPANY_ITEM_CODE_UQ UNIQUE (company_id, item_code),
    CONSTRAINT ITEMS_COMPANY_ID_FK        FOREIGN KEY (company_id)       REFERENCES companies(id),
    CONSTRAINT ITEMS_ITEM_CATEGORY_ID_FK  FOREIGN KEY (item_category_id) REFERENCES item_categories(id)
);

-- SKU codes — globally unique; one item can have many SKUs
CREATE TABLE IF NOT EXISTS item_skus (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id    BIGINT         NOT NULL,
    sku_code   VARCHAR(100)   NOT NULL,
    unit_price NUMERIC(19, 4) NOT NULL,
    created_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT ITEM_SKUS_SKU_CODE_UQ UNIQUE (sku_code),
    CONSTRAINT ITEM_SKUS_ITEM_ID_FK  FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);

-- One row per price type per item
CREATE TABLE IF NOT EXISTS item_prices (
    id         BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id    BIGINT         NOT NULL,
    price_type VARCHAR(20)    NOT NULL, -- UNIT_PRICE | COST_PRICE | FOCAL_PRICE | MARKDOWN_PRICE
    amount     NUMERIC(19, 4) NOT NULL,
    created_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT ITEM_PRICES_ITEM_PRICE_TYPE_UQ UNIQUE (item_id, price_type),
    CONSTRAINT ITEM_PRICES_ITEM_ID_FK         FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS item_tags (
    item_id BIGINT      NOT NULL,
    tag     VARCHAR(50) NOT NULL,
    PRIMARY KEY (item_id, tag),
    CONSTRAINT ITEM_TAGS_ITEM_ID_FK FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE
);

-- ============================================================
-- Brands
-- ============================================================

CREATE TABLE IF NOT EXISTS brands (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT BRANDS_COMPANY_NAME_UQ UNIQUE (company_id, name),
    CONSTRAINT BRANDS_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- ============================================================
-- Warehouses
-- ============================================================

CREATE TABLE IF NOT EXISTS warehouses (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT       NOT NULL,
    code       VARCHAR(100),
    name       VARCHAR(255) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by VARCHAR(100),
    updated_by VARCHAR(100),
    CONSTRAINT WAREHOUSES_COMPANY_CODE_UQ UNIQUE (company_id, code),
    CONSTRAINT WAREHOUSES_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id)
);

-- ============================================================
-- Employees
-- ============================================================

CREATE TABLE IF NOT EXISTS employees (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    BIGINT       NOT NULL,
    user_id       BIGINT,
    employee_code VARCHAR(100) NOT NULL,
    first_name    VARCHAR(255) NOT NULL,
    last_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255),
    phone         VARCHAR(50),
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    created_by    VARCHAR(100),
    updated_by    VARCHAR(100),
    CONSTRAINT EMPLOYEES_COMPANY_CODE_UQ UNIQUE (company_id, employee_code),
    CONSTRAINT EMPLOYEES_COMPANY_ID_FK   FOREIGN KEY (company_id) REFERENCES companies(id),
    CONSTRAINT EMPLOYEES_USER_ID_FK      FOREIGN KEY (user_id)    REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS employee_tags (
    employee_id BIGINT      NOT NULL,
    tag         VARCHAR(50) NOT NULL,
    PRIMARY KEY (employee_id, tag),
    CONSTRAINT EMPLOYEE_TAGS_EMPLOYEE_ID_FK FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE
);

-- ============================================================
-- Audit log — append-only record of all entity changes
-- ============================================================

CREATE TABLE IF NOT EXISTS audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(100) NOT NULL,
    entity_id   BIGINT,
    action      VARCHAR(20)  NOT NULL,
    changed_by  VARCHAR(100),
    changed_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    changes     TEXT
);

-- ============================================================
-- Seed data
-- The application's DataInitializer also runs these upserts on
-- every startup, so both paths are safe to run concurrently.
-- ============================================================

INSERT INTO permissions (name, description) VALUES
    ('MANAGE_SYSTEM',        'Security - System Manage'),
    ('VIEW_USER',            'Security - User View'),
    ('CREATE_USER',          'Security - User Create'),
    ('UPDATE_USER',          'Security - User Update'),
    ('DELETE_USER',          'Security - User Delete'),
    ('VIEW_ROLE',            'Security - Role View'),
    ('CREATE_ROLE',          'Security - Role Create'),
    ('UPDATE_ROLE',          'Security - Role Update'),
    ('DELETE_ROLE',          'Security - Role Delete'),
    ('VIEW_ITEM',            'Maintenance - Item View'),
    ('CREATE_ITEM',          'Maintenance - Item Create'),
    ('UPDATE_ITEM',          'Maintenance - Item Update'),
    ('DELETE_ITEM',          'Maintenance - Item Delete'),
    ('VIEW_COST_PRICE',      'Maintenance - Item Cost Price View'),
    ('VIEW_BRAND',           'Maintenance - Brand View'),
    ('CREATE_BRAND',         'Maintenance - Brand Create'),
    ('UPDATE_BRAND',         'Maintenance - Brand Update'),
    ('DELETE_BRAND',         'Maintenance - Brand Delete'),
    ('VIEW_ITEM_CATEGORY',   'Maintenance - Item Category View'),
    ('CREATE_ITEM_CATEGORY', 'Maintenance - Item Category Create'),
    ('UPDATE_ITEM_CATEGORY', 'Maintenance - Item Category Update'),
    ('DELETE_ITEM_CATEGORY', 'Maintenance - Item Category Delete'),
    ('VIEW_WAREHOUSE',       'Maintenance - Warehouse View'),
    ('CREATE_WAREHOUSE',     'Maintenance - Warehouse Create'),
    ('UPDATE_WAREHOUSE',     'Maintenance - Warehouse Update'),
    ('DELETE_WAREHOUSE',     'Maintenance - Warehouse Delete'),
    ('VIEW_EMPLOYEE',        'HR - Employee View'),
    ('CREATE_EMPLOYEE',      'HR - Employee Create'),
    ('UPDATE_EMPLOYEE',      'HR - Employee Update'),
    ('DELETE_EMPLOYEE',      'HR - Employee Delete')
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

INSERT INTO roles (name, display_name) VALUES
    ('ADMIN',        'Administrator'),
    ('SYSTEM_ADMIN', 'System Administrator'),
    ('SUPER_ADMIN',  'Super Administrator')
ON CONFLICT (name) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON true
WHERE (r.name = 'SYSTEM_ADMIN' AND p.name IN (
    'VIEW_USER', 'CREATE_USER', 'VIEW_ROLE',
    'VIEW_ITEM', 'CREATE_ITEM', 'UPDATE_ITEM',
    'VIEW_BRAND', 'CREATE_BRAND', 'UPDATE_BRAND',
    'VIEW_ITEM_CATEGORY', 'CREATE_ITEM_CATEGORY', 'UPDATE_ITEM_CATEGORY',
    'VIEW_WAREHOUSE', 'CREATE_WAREHOUSE', 'UPDATE_WAREHOUSE',
    'VIEW_EMPLOYEE', 'CREATE_EMPLOYEE', 'UPDATE_EMPLOYEE'
))
OR (r.name = 'SUPER_ADMIN' AND p.name IN (
    'MANAGE_SYSTEM',
    'VIEW_USER', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER',
    'VIEW_ROLE', 'CREATE_ROLE', 'UPDATE_ROLE', 'DELETE_ROLE',
    'VIEW_ITEM', 'CREATE_ITEM', 'UPDATE_ITEM', 'DELETE_ITEM', 'VIEW_COST_PRICE',
    'VIEW_BRAND', 'CREATE_BRAND', 'UPDATE_BRAND', 'DELETE_BRAND',
    'VIEW_ITEM_CATEGORY', 'CREATE_ITEM_CATEGORY', 'UPDATE_ITEM_CATEGORY', 'DELETE_ITEM_CATEGORY',
    'VIEW_WAREHOUSE', 'CREATE_WAREHOUSE', 'UPDATE_WAREHOUSE', 'DELETE_WAREHOUSE',
    'VIEW_EMPLOYEE', 'CREATE_EMPLOYEE', 'UPDATE_EMPLOYEE', 'DELETE_EMPLOYEE'
))
ON CONFLICT DO NOTHING;

INSERT INTO companies (name) VALUES ('Norbiz')
ON CONFLICT DO NOTHING;

-- Passwords are hashed at insert time via pgcrypto (BCrypt, cost 10).
-- Change the plaintext values here before running on a new environment.
INSERT INTO users (username, email, password) VALUES
    ('admin',        'admin@norbiz.com',        crypt('change-me-admin',        gen_salt('bf', 10))),
    ('super_admin',  'super.admin@norbiz.com',  crypt('password',  gen_salt('bf', 10))),
    ('system_admin', 'system.admin@norbiz.com', crypt('change-me-system-admin', gen_salt('bf', 10)))
ON CONFLICT (username) DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u JOIN roles r ON true
WHERE (u.username = 'admin'        AND r.name = 'ADMIN')
   OR (u.username = 'super_admin'  AND r.name = 'SUPER_ADMIN')
   OR (u.username = 'system_admin' AND r.name = 'SYSTEM_ADMIN')
ON CONFLICT DO NOTHING;

INSERT INTO user_companies (user_id, company_id)
SELECT u.id, c.id FROM users u JOIN companies c ON true
WHERE u.username = 'super_admin' AND c.name = 'Norbiz'
ON CONFLICT DO NOTHING;
